### ISSUE TITLE
  Error: The value is not supported: [Object: null prototype] 

### ISSUE THREAD

**Issue by facusantillo** [MrShoenel/ff-fingerprinter#1]
Description: Downloaded the repo, installed ffmpeg, ffprobe, mediainfo. Run the tests and this error is coming up. 

Debugged it and find out when generating the hash, it's merging an empty object recursively producing this error.

Line:

`/** @type {ProbeResultWithHashInfo} */
    const resultWithHashInfo = mergeObjects({}, probeResult);
    resultWithHashInfo.hashInfo = {};`

Tried it by removing the `mergeObjects` and using only probeResult and it works.

Any workaround? Why is it failing?

**Comment by MrShoenel** [comment]
Hey!
Thanks for reporting the problem, it was because of a null-prototype object that could not be serialized. Updated to v1.2.3 and the tests are passing again. I'll leave this open now but please close it should it resolve your problem.

**Comment by facusantillo** [comment]
I'll re-test it tomorrow morning and update the status here. Ty!
